userCheck.xml
=> userCheck.xmlの追加

check_user.xml, userCheck.xml
#1 
指摘のあった部分を修正。
ただ、英語部分がこれでよいかは自信がないです。
あと、以前アップロードしたデータを削除しました(ファイル名が現在のものと変わっているため)
=> Mr task 2018 2 21

userCheck.xml
=> UserCheck.xmlの修正

LINENotify.xml
#8 
length()をnullに使うようになってしまっていたので、修正しました。
=> LINENotify.xmlの修正

userCheck.xml
=> UserCheck.xml

LINENotify.xml
=> LINENotify.xml

Line-pushNotify.xml
=> last-modifiedの位置を先頭に変更

box_webhook_create.xml, box_webhook_delete.xml, box_webhook_json_parse.xml
=> help-page-urlの変更と英語表現の改善

GoogleDrive-folderDelete.xml
=> 削除アドオンのアドオン名を修正

GoogleDrive-folderCreate.xml, GoogleDrive-folderDelete.xml, GoogleDrive-permissionCreate.xml
=> ログ出力に関する修正

GoogleDrive-folderDelete.xml
=> ID出力・上限超過・繰り返し処理の変更

GoogleDrive-folderCreate.xml, GoogleDrive-folderDelete.xml, GoogleDrive-permissionCreate.xml
=> "Google ドライブ"に修正・varをletかconstに

GoogleCalendar-insertEvent.xml
=> Google calendar予定追加アドオン

google-drive-file-delete.xml, google-drive-folder-create.xml, google-drive-permission-create.xml
=> ラベルを修正・「生成」を「作成」に・License情報を追加

slack-chat-post-bots.xml, slack-chat-post-webhook.xml
=> 誤字修正&スペースを:のあとに

google-drive-file-delete.xml, google-drive-folder-create.xml, google-drive-permission-create.xml
=> configの表記を修正

google-drive-file-delete.xml
=> last-modifiedを変更

slack-chat-post-bots.xml, slack-chat-post-webhook.xml
=> configのlabelを変更

slack-file-upload-bots.xml
=> Slackにファイルをアップロードするアドオン

slack-chat-post-bots.xml, slack-file-upload-bots.xml
=> as_user を true に

slack-file-upload-bots.xml
=>  アップロード:指摘の部分修正(2)

slack-chat-post-bots.xml, slack-file-upload-bots.xml
=> return使用に変更、configのlabel修正

any-website-file-download.xml
=> ファイルをダウンロードするアドオン

GoogleSheets-appendCells.xml, GoogleSheets-getIdsLabels.xml
=> Google sheet関連アドオン

slack-file-upload-bots.xml
config(I1→C3)とhelp-page-urlを更新
=> configとhalp-page-urlを修正

any-website-file-download.xml
configのlabel(C2,C3)とhelp-page-urlの日本語のほうを更新
=> configとhelp-page-urlを修正

converter-dateToJpEra.xml
=>  「令和」暫定対応を削除

GoogleSheets-appendCells.xml
=> Google sheet 行追加アドオン

google-drive-folder-search.xml
テストは https://docs.google.com/spreadsheets/d/1zd-2Jx6dlNuKuYD5q58Mc23eHPBNohvdEkFazcSMNBM/edit?usp=sharing
=> Google drive フォルダ検索アドオン

converter-dateToJpEra.xml
設定で日時／日付型 YMD だけ設定できること。他は設定できないこと。
プロセス上で動かしてみて、動作すること。日付型 YMD、正常系のみ。
以上のことを確認済み。
=> 日付型の対象を年月日タイプのみに制限する

google-sheets-choice-batchget.xml, google-sheets-row-append.xml
=>  label.summary等変更

google-drive-folder-search.xml
=> help-page-url更新

Box-upload.xml
=> Box uploadアドオン

box-file-upload.xml
=>  summaryを追加

google-sheets-row-append.xml
=> TEXTAREAに変更

box-file-upload.xml
=> C2とC3を入れ替え

box-file-delete.xml, box-folder-create.xml, box-folder-search.xml, box-sharedLink-create.xml
https://docs.google.com/spreadsheets/d/1zVXLzcI9rk67oHJ53bduLr91iUhpL8cnYvj7yoIFmxo/edit?usp=sharing
テスト済み。
=> Box フォルダ作成アドオン

box-file-upload.xml
=> config変更をコードに反映

google-drive-folder-search.xml
=> フォルダが無いときエラーになるよう変更

box-folder-create.xml, box-folder-search.xml
=> Boxフォルダ作成-configの編集

google-drive-file-delete.xml
「サービスタスク（Google ドライブ: ファイル削除）名前の変更」に対応。
=> 削除アドオン:label,summary,configの変更

box-folder-delete.xml, box-folder-sharedLink-create.xml
https://docs.google.com/spreadsheets/d/1qvQ5-U9uOOyysww9_kt10CQhHhV6e9lO0A-4nWOvWAU/edit?usp=sharing
テスト済みです。
=> Box:フォルダ削除アドオン

box-folder-delete.xml, box-folder-link-create.xml, box-folder-search.xml
=> Box addons 諸々の修正

box-folder-search.xml
11個のフォルダがあるフォルダに対してlimit=1とlimit=1000で検索し、前者はエラー、後者は成功することを確認。
=> 1001件以上検索できるように変更

box-folder-search.xml
=> 検索:ラベルとコードを修正

box-folder-link-create.xml
8/22 12:00を送り、2019-08-21T20:00:00-07:00に設定されることを確認。
=> 共有:タイムゾーンを使用するように

box-folder-link-create.xml
=> 共有:タイムゾーン周りの改良

sendgrid-transaction-send.xml
https://docs.google.com/spreadsheets/d/1xGc5HTRWlN1i0aVBQmj-2_fuTRoS12n7Wrvi2xwyqUo/edit?usp=sharing
テスト済みです。
=> SendGrid(テストまで)

converter-table-to-excelcsv.xml
summary の項目を追加　「テーブル型データ項目の値を、Excel 対応の CSV としてファイル型データ項目に格納します。」英語は「Stores the values in a Table type data item into a File type data item as an Excel compatible CSV.」
license の項目を追加
A のラベル設定項目を「対象のテーブル型データ項目」に修正　英語は「Select target TABLE DATA」
Cのラベル設定項目を「CSVファイルが格納されるファイル型データ項目」に修正　英語は「Select FILE DATA as an Excel compatible CSV」
myTsv 変数を定義している箇所を変更
=> summary,license 追加　ラベル設定項目修正　myTsv変数定義箇所変更

sendgrid-add-contact.xml, sendgrid-mail-bulk-send.xml
=> Sendgrid:メール送信のファイル名等変更

converter-excelcsv-to-table.xml
=> A: の後ろにスペース追加

google-drive-file-copy.xml
=> サービスタスク (Google ドライブ: ファイルコピー)

google-drive-file-copy.xml
=> help-page-urlを更新

converter-textfile-to-string.xml
labelの文言を以下のように修正しました。
Text ファイル→テキストファイル
TextFile→Text Fileに修正
ご確認よろしくお願いします。
=> label:Text ファイル→テキストファイル、TextFile→Text Fileに修正

google-sheets-append-table.xml
テスト : https://docs.google.com/spreadsheets/d/122G8ylw8ql-Io9B3_ZEjalReAddPHNScm6CVaNXMmiE/edit#gid=0
=> Google スプレッドシート: 行追加 (テーブル型データ項目) 関数分割ほか

google-sheets-row-append-by-table.xml
oauth2-setting-name="https://www.googleapis.com/auth/spreadsheets" を追加。
=> Google スプレッドシート: 行追加 (テーブル型データ項目)

onedrive-file-upload.xml, onedrive-folder-create.xml
https://docs.google.com/spreadsheets/d/19kH-O1XcqIXj9tys3AsvP5OSgmOHw6X2VgjE8bRQ4G4/edit#gid=334762475
=> OneDrive:ファイルアップロード

onedrive-file-delete.xml
https://docs.google.com/spreadsheets/d/1fnwEfR_xv2kMBTY38fU1FF5iijLtUYSxHEjbJQAUQ0k/edit#gid=2063973824
=> OneDrive:ファイル/フォルダ削除

onedrive-file-upload.xml
=> Office 365 OneDrive: ファイルアップロード　の作成

onedrive-file-copy.xml
@suese-sayaka さん
コードレビューをお願いいたします。
=> OneDrive: ファイルコピー　の作成

onedrive-file-copy.xml
=> ver2020-06-05 ラベルを変更

onedrive-file-delete.xml
=> OneDrive フォルダ/ファイル削除

onedrive-file-upload.xml
@suese-sayaka さん
コードレビューをお願いいたします。
=> OneDrive: ファイルアップロード　共有ライブラリへの対応　エンジンを GraalJS に変更する

onedrive-folder-create.xml
@suese-sayaka さん
コードレビューをお願いいたします。
=> Office 365 OneDrive: フォルダ作成　共有ライブラリへの対応　エンジンを GraalJS に変更する

onedrive-file-delete.xml
@suese-sayaka さん
コードレビューをお願いいたします。
=> OneDrive: ファイル / フォルダ削除　共有ライブラリへの対応　エンジンを GraalJS に変更する

onedrive-file-copy.xml
ご確認のうえ、問題なければマージをお願いいたします。
アドオン名の変更のついでに、他のOneDriveのアドオンに合わせて変数名やエラーメッセージなど修正しました。
=> Microsoft 365 OneDrive for Business: ファイルコピー のアドオン名の変更

onedrive-file-upload.xml
=> Microsoft 365 OneDrive for Business: ファイルアップロード のアドオン名の変更

onedrive-folder-create.xml
=> Microsoft 365 OneDrive for Business: フォルダ作成 のアドオン名の変更

onedrive-file-delete.xml
=> Microsoft 365 OneDrive for Business: ファイル / フォルダ削除 のアドオン名の変更

box-file-upload.xml
=> T7245:Box: ファイルアップロード

kintone-record-add.xml
=> T7344 kintone: レコード追加　の作成

google-drive-file-delete.xml
=> T7366: Google ドライブ: ファイル / フォルダ削除 の更新

excel-row-insert.xml
=> T7308: Office 365 Excel: 行追加　の作成

kintone-record-add.xml
コードを修正しました。
お手数ですがマージのほど、お願いいたします。
=> T7344: kintone: レコード追加　ループ回数を修正

google-drive-file-delete.xml
指定したファイルID / フォルダIDが空行の場合は無視するように
=> T7384: Google ドライブ: ファイル / フォルダ削除

any-website-file-download.xml
t7402
`engine-type`を`2`に変更しました。
レビューをお願いします。
=> T7402: engine を「2」に変更

kintone-record-get.xml
=> T7345: kintone: レコード取得　の作成

any-website-file-download.xml, generator-textfile.xml
- 最終更新日
- エンジン番号 1→2
- function main() {} の中を関数化
=> T7403: ジェネレータ（テキストファイル）　エンジンを GraalJS に変更する

kintone-choice-download.xml
=> T7428: kintone: 選択肢データの一括取得　の作成

box-file-upload.xml
=> T7245:Box: ファイルアップロード より大きいサイズのファイルをアップロードできるように

box-file-upload.xml
=> T7245; Box アップロード

kintone-record-add.xml
=> T7344: kintone: レコード追加　認証設定のラベルを変更

kintone-record-get.xml
=> T7345: kintone: レコード取得　認証設定のラベルを変更

kintone-choice-download.xml
=> T7428: kintone: 選択肢データの一括取得　認証設定のラベルを変更

converter-excelcsv-to-table.xml
t7406 で複数のファイルがコミットされていた問題を修正する。
下記コマンドを実行した後、本プルリクを作成した。
```
git checkout master
git pull origin master # master を最新に
git branch t7406-new # branch 作成
git checkout t7406-new # branch 切り替え
git checkout t7406 converter-excelcsv-to-table.xml # 元の作業 branch から特定ファイルをマージ
```
=> T7406-new:コンバータ（Excel-CSV ファイル to テーブル型データ）　エンジンを GraalJS に変更する

kintone-record-update.xml
ヘルプページURLの修正漏れに気付きました。
お手数ですが再マージのほど、お願いいたします。
=> T7503 kintone: レコード更新　ヘルプページのURLを修正

converter-table-to-excelcsv.xml
=> T7405:コンバータ（テーブル型データ to Excel-CSV ファイル）　エンジンを GraalJS に変更する

gmail-message-get.xml
詳細な動作確認とアイコンの設定はまだですが、仕様について何かあればコメントいただけるようにプルリクエストを作成します。
=> T7516：Gmail: メール取得　の作成

converter-textfile-to-string.xml
=> T7404：コンバータ（テキストファイル to 文字型データ）　エンジンを GraalJS に変更する

kintone-file-download.xml
一通りの動作確認が出来ましたので、レビューをお願いいたします。
=> T7530 kintone: ファイルダウンロード　の作成

kintone-file-add.xml
=> T7531：kintone: ファイル追加　の作成

kintone-file-upload.xml
=> T7531：kintone: ファイルアップロード　ファイル名、ラベルを変更

kintone-record-delete.xml
=> kintone: レコード削除　の作成

google-drive-folder-create.xml
以下の点を修正しました。
- userIDがない場合にUser not foundと表示されるように修正。
- 関数化とJSDoc形式のコメントを追加。
=> T7393:Google ドライブ: フォルダ作成　エンジンを Nashorn から GraalJS に変更する

google-sheets-row-append.xml
畠中さん
ソースを修正しました。ご確認お願いします。
70～73行は削除した方がよいでしょうか？
=> change engine from Nashorn to GraalJS

gmail-message-label-remove.xml
=> T7638:Gmail: メールのラベルを解除　の作成

google-sheets-row-append.xml
畠中さん
https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId} の Status を確認する処理を追加しました。
ご確認よろしくお願いします。
=> Add the process to check the return value of API

google-drive-folder-search.xml
`incluedeItemsFromAllDrives` -> `includeItemsFromAllDrives` に修正
=> T7394:パラメータを修正

google-drive-folder-create.xml
巽さん
Google 連携まわりのコード変更しました。
httpClient.begin().googleOAuth2()
ご確認よろしくお願いします。
=> modify about Google Connectivity

google-calendar-event-insert.xml
- ユーザIDのバグを修正
57行目 `quserDao.findById(parseInt(userId))` -> 47行目 `configs.getObject()`
=> T7553:Google カレンダー: 予定追加　設定したユーザが削除されている場合、ID 0 のユーザを設定したものとして処理される

any-website-file-download.xml
巽さん
レスポンス全体のログが出力がされないように修正しました。ご確認よろしくお願いします。
=> quit log output of response

google-drive-folder-search.xml
=> T7657: Google ドライブ: フォルダ検索　Google API の変更への対応

box-folder-create.xml
#7668
- 設定名の変更。OAuth2 設定名 -> OAuth2 設定
- bearer() の使用を authSetting() に変更
- last-modified の更新
=> OAuth2 認証まわりのコード変更

box-folder-delete.xml
改修点
- 設定名の変更。OAuth2 設定名 -> OAuth2 設定
- bearer() の使用を authSetting() に変更
- last-modified の更新
- 成功時・エラー時それぞれのログ出力文言を変更
=> Box: フォルダ削除　OAuth2 認証まわりのコード変更

box-file-delete.xml
=> Box: ファイル削除

kintone-record-add.xml
レビューをお願いいたします。
* Basic 認証に対応しました
* レスポンス本文のログ出力をエラー時のみにしました
=> T7755: kintone: レコード追加　Basic 認証に対応する

box-file-move.xml
=> Box: ファイル移動　の作成

box-file-move.xml
IDは変化しないためC4とC5、それに関連するコードを削除
同時にコンフィグ名とログ出力を変更
=> C4,C5と関連部分を削除

google-calendar-event-delete.xml
ドキュメント: https://developers.google.com/calendar/v3/reference/events/delete
=> Google カレンダー: 予定削除

start_event/kintone-record-datetime-field.xml
=> T7795: 開始: kintone: レコード 日時フィールド　Basic 認証に対応

kintone-record-delete.xml
巽さん
Basic認証の処理を追加しました。
ソースレビューをお願いします。
=> support basic authentication

onedrive-file-copy.xml
OAuth2 認証周りのコード修正と、リファクタリングを行いました。
HTTP リクエストに成功した場合はログ出力を行わない変更も加えています。
レビューをお願いします。
=> T7798: Microsoft 365 OneDrive for Business: ファイル / フォルダコピー　OAuth2 認証周りのコード修正

excel-row-insert.xml
レビューをお願いします。
HTTP リクエストに成功した場合はログ出力を行わない等、リファクタリングも併せて行っています。
=> T7801: Microsoft 365 Excel: 行挿入　OAuth2 認証まわりのコード変更

kintone-file-download.xml
=> T7793: kintone: ファイルダウンロード　Basic 認証に対応

kintone-file-upload.xml
=> T7792: kintone: ファイルアップロード　Basic 認証に対応

google-calendar-event-move.xml
ドキュメント：
https://developers.google.com/calendar/v3/reference/events/move
=> T7737:Google カレンダー: 予定のカレンダー移動　の作成

google-bigquery-data-insert.xml
=> T7639: Google BigQuery: データ追加　の作成

onedrive-file-upload.xml
=> T7886: Microsoft 365 OneDrive for Business: ファイルアップロード　ファイルの上書きも許可できるように

google-bigquery-data-insert.xml
=> T7639: Google BigQuery: データ追加　oauth2-setting-name を変更

onedrive-file-delete.xml
巽さん
OAuth2 認証まわりとログ出力を変更しました。ご確認よろしくお願いします。
=> change around OAuth2 authentication

onedrive-folder-create.xml
=> T7799: Microsoft 365 OneDrive for Business: フォルダ作成　OAuth2 認証まわりのコード変更

kintone-choice-download.xml
=> T7794: kintone: 選択肢データの一括取得　Basic 認証に対応

google-sheets-sheet-add.xml
https://github.com/Questetra/Addon-XML/pull/336 と同じ内容です。
上記のプルリクエストには、2つ(google-sheets-sheet-add.xml, google-sheets-add-new-sheet.xml)ファイルが含まれていました。そのため、google-sheets-add-new-sheet.xml のほうを対象から除外し、push し本プルリクエストを作成しました。
=> T7853-new:Google スプレッドシート: シート追加の作成

google-sheets-row-get.xml
@tatsumiQ  さん
ファイル名を修正しました。
convertTypeAndSetData() を、`/*` と `*/` で複数行コメントアウトしました。
ご確認をお願いいたします。
=> Update and rename google-sheets-row-get to google-sheets-row-get.xml

google-drive-permission-create.xml
=> Google ドライブ: 共有設定　新しい config form-type を使用して作り直す

google-sheets-row-update.xml
@tatsumiQ  さん
ソースコードを修正しました。
ご確認をお願いいたします。
=> 日付形式のテキスト、数値をテキストで更新するよう対応

google-calendar-event-insert.xml, google-drive-file-delete.xml, google-drive-folder-create.xml, google-drive-folder-search.xml, google-sheets-choice-batchget.xml, google-sheets-file-create.xml, google-sheets-row-append-by-table.xml, google-sheets-row-append.xml
各ファイルの、ヘルプページのパスを /addons/ から /bpmn-icons/ に変更しました。
ご確認をお願いいたします。
=> T7992 ヘルプページのパスを /addons/ から /bpmn-icons/ に変更

converter-excelcsv-to-table.xml
非推奨のメソッドから新しいメソッドに変更しました。
`com.questetra.bpms.core.model.formdata.ListArray` (廃止予定) を `ScriptListArray`
`com.questetra.bpms.core.model.formdata.ListArray.ListRow` (廃止予定)を`ScriptListArray.ScriptListRow`に
=> T7985:コンバータ（Excel-CSV ファイル to テーブル型データ）　ScriptListArray を使用するコードに変更

excel-row-insert.xml, onedrive-file-copy.xml, onedrive-file-delete.xml, onedrive-file-upload.xml, onedrive-folder-create.xml
それぞれの定義ファイルのヘルプページのパスを変更しました。
ご確認をお願いいたします。
=> T7993 Microsoft 365 関連アイテム ヘルプページのパスを/addons/ から /bpmn-icons/ に変更

generator-textfile.xml
色々よく分かっていないのですが、コードを作成しました。
何が良くないかとか、理解できていないかとか、教えてください。
=> 単体テストのコードを追加

box-file-move.xml
fields 属性を指定しました。
単体テストコードを追加しました。
ご確認をお願いいたします。
=> fields 属性を指定　単体テストコードを追加

box-file-upload.xml
畠中さん
API 呼び出し時に fields 属性を指定しました。またテストコードもそれに伴い変更しました。
レビューをお願いします。
=> specified field attributes

box-collaboration-delete.xml
畠中さん
テストコードを追加しました。
出力ログを見やすいようにstatus:とエラコードの間にスペースを入れました。
レビューをお願いします。
=> add unit test code

google-drive-permission-create.xml
・requestの名称変更できていなかった部分を修正
・通信数の計算が間違っていた部分を修正
=> t7887:誤り部分2箇所を修正

box-folder-search.xml
単体テストコードを追加しました。
ご確認をお願いいたします。
=> 単体テストコードを追加

google-sheets-sheet-delete.xml
畠中さん
テストコードを追加しました。レビューをお願いします。
=> add unit test code - google-sheets-sheet-delete

box-folder-delete.xml
=> Box: フォルダ削除　単体テストの追加

box-collaboration-delete.xml
巽さん
レビューをお願いします。
コラボレーションが一つもないケースについて修正しました。それに伴い単体テストも追加しました。
=> fixed case of no collaborasion.

box-file-link-delete.xml
=> T8082:Box: ファイル共有リンク削除 単体テストの追加

box-file-link-delete.xml
=> T8082:last-modifiedを更新

google-sheets-file-create.xml
=> OAuth2 認証まわりのコード変更  単体テストコード追加

google-drive-folder-create.xml
畠中さん
単体テストコードを追加しました。ご確認よろしくお願いします。
=> add unite test code

box-folder-link-create.xml
=> T8085:last-modifiedを更新

google-calendar-event-delete.xml
畠中さん
レビューをお願いします。
・単体テストコードを追加
・ハイフンを含むカレンダー ID でも処理できるように修正
=> add unite test code and fix to handle if calenderID contains hypens

google-bigquery-data-insert.xml
単体テストを追加し、一箇所だけ script 内のコードを修正しました。
レビューをお願いします。
=> T8313: Google BigQuery: データ追加　単体テストの追加

google-calendar-event-move.xml
畠中さん
レビューをお願いします。
・Calender IDのパラメータチェックを変更
・単体テストコードを追加
=> change Calender IDs parameter check, add unit test code

google-sheets-sheet-copy.xml
Google スプレッドシート: シートコピー　単体テストの追加
=> T8222:単体テストを追加

onedrive-folder-create.xml
畠中さん
レビューをお願いします。
・単体テストコードを作成
・summary を変更
=> add unit test code, modify summary

onedrive-file-delete.xml
畠中さん
レビューをお願いします。
・単体テストコードを追加
・summaryを変更
=> add unite test code, change summary

slack-chat-post-bots.xml
単体テストコードは未対応です。
Attachment でリンクが設定されていたら、テキストが空でも、メンションを指定できた方がよいかなと思いスクリプトを書きました。
=> t8491 テキストの最後にメンションを指定

slack-file-upload-bots.xml
スクリプトコードの
.multipart('file',file)
.multipart('channels',channel)
を、検証するテストコードですが、「Box:ファイルアップロード」を参考にして、.multipart('file',file)　のテストコードは作成できて、ビルドがとおりました。
.multipart('channels',channel)
を検証するテストコードですが、「Box:ファイルアップロード」の、.multipart('attributes', JSON.stringify(attributes))　の部分を参考にしてみたのですが、ビルドでエラーが出てしまいます。
テストコードを以下のようにして、エラーになってしまうのですが、もし、他のテストコードを参考にできるアイテムがあったら教えてください。
const channel = body.get('channel');
expect(channel).toEqual(`${channels}`);
//    expect(channel.getName()).toEqual(`${channels}`);
=> t8323&8493  Slack: ファイルアップロード (Bots)

onedrive-file-copy.xml
畠中さん
レビューをお願いします。
・サマリーを変更
・単体テストコードを追加
=> change summary, add unite test code

any-website-file-download.xml
定義ファイルを修正しました。
テストコードを修正しました。
ご確認をお願いいたします。
=> t8513（任意Webサイト）: ファイル ダウンロード  HTTP認証設定/ summaryの変更

kintone-record-delete.xml
レビューをお願いします。
・単体テストコードを追加
・summaryを変更
=> T8321: kintone: Delete Record - add unite test code/change summary

kintone-record-update.xml
単体テストの追加、summary を変更しました。
ご確認をお願いいたします。
=> t8320 kintone: レコード更新　単体テストの追加／summary の変更

slack-chat-post-bots.xml
スコープの異なる HTTP 認証設定を参照できるように。
既存の設定は deprecated に。
=> 新しい form-type="OAUTH2" の設定を追加。

kintone-file-upload.xml
テストコード作成とsummary の変更を行いました。
ご確認をお願いします。
=> 8595: kintone: ファイルアップロード　単体テストの追加／summary の変更

generator-textfile.xml
レビューをお願いします。
・C5 をrequired="true" から、required="false"に変更しました。
=> t8500: Generate Text File - Remove required of content type

generator-textfile.xml
レビューをお願いします。
summaryとconfigsの英語表記を修正しました。
・summary 日本語に合わせる
・configs C2の文頭を大文字に
=> t8500: Generate Text File - Change summary and configs

kintone-file-download.xml
単体テストの追加と summary の変更を行いました。
ご確認をお願いいたします。
=> t8596: kintone: ファイルダウンロード　単体テストの追加／summary の変更

converter-excelcsv-to-table.xml
レビューをお願いします。
以下を変更しました。
・summary
・テストコードで処理に失敗する場合の処理
=> t8667: Converter (Excel-CSV FILE to Table type data)-change summary and error cases

box-collaboration-delete.xml
レビューをお願いします。
以下を変更しました。
・summary
・異常系のテストの形式
=> t8747: Box: Delete Collaboration - Change summary and error cases

box-collaboration-add.xml
レビューをお願いします。
以下を変更しました。
・summary
・異常系のテストの形式
=> t8748: Box: Add Collaboration - Change summary and error cases

box-file-copy.xml
- フォーマットをかけたため、変更箇所が多くなっています
- 成功時のログ出力をやめ、代わりにエラーメッセージにステータスコードを含めるようにしました
=> T8756: Box: ファイルコピー　Summary の変更／Nashorn Compatible モード取りやめを見越した単体テストの改良

box-file-move.xml
- 成功時のログを削除しました
- エラーメッセージにステータスコードを含めるようにしました
=> T8755: Box: ファイル移動　Summary の変更／Nashorn Compatible モード取りやめを見越した単体テストの改良

box-file-delete.xml
フォーマットをかけたので、変更箇所が多くなっています。
Summary の変更、単体テストの改良のほか、ログ出力を整形してステータスコードをエラーメッセージに含めるようにしました。
=> T8752: Box: ファイル削除　Summary の変更／Nashorn Compatible モード取りやめを見越した単体テストの改良

box-file-link-delete.xml
定義ファイルをフォーマットしたため、変更箇所が多くなっています。
=> T8753: Box: ファイル共有リンク削除　Summary の変更／Nashorn Compatible モード取りやめを見越した単体テストの改良

box-file-link-create.xml
=> T8754: Box: ファイル共有リンク作成　Summary の変更／Nashorn Compatible モード取りやめを見越した単体テストの改良

box-folder-link-delete.xml
レビューをお願いします。以下を変更しました。
・summary
・異常系のテストの形式
・ログ出力の整形(他のコードに合わせて、エラーメッセージの改行を削除)
=> t8855: Box: Delete Shared Link of Folder - Change summary and error cases

google-drive-folder-create.xml
レビューをお願いします。
Summary の変更、単体テストの改良のほか、ログ出力を整形し、フォーマットをかけました。
・Summary の変更
・ログ出力の整形（形式を整えただけ  Box: ファイル削除等と揃えました ）
・OK 時のログ出力（ステータスコードの削除  Box: ファイル削除等と揃えました）
=> t8885 Google ドライブ: フォルダ作成　Summary の変更／単体テストの改良

google-drive-permission-create.xml
Summary を変更し、フォーマットをかけました。
レビューをお願いします。
=> t8886 Google ドライブ: 共有リンク作成　Summary の変更

google-sheets-sheet-copy.xml
レビューをお願いします。
以下を変更しました。
・summary
・成功時のログ出力を削除
=> t8875: Google Sheets: Copy Sheet - Change summary and delete success log

google-sheets-row-update.xml
レビューをお願いします。
以下を変更しました。
・summary
・異常系のテストの形式
=> t8871: Google Sheets: Update Row - Change summary and error cases

google-drive-file-delete.xml
レビューをお願いします。
Summary の変更、単体テストの改良のほか、ログ出力を整形（Box ファイル削除等と揃えましたt）しました。
=> 8884: Google ドライブ: ファイル / フォルダ削除　Summary変更／単体テスト改良

box-folder-delete.xml
レビューをお願いします。
テストコードのメソッド名を修正し、単体テストを実行できることを確認しました。
英語の summary を修正しました。
=> t8854: Box: フォルダ削除　Summary の変更／単体テストの改良

google-drive-file-delete.xml
レビューをお願いします。
summary と、コンフィグを修正しました。
=> t8884 Google ドライブ: ファイル / フォルダ削除 Summary変更／単体テスト改良

google-drive-folder-search.xml
レビューをお願いします。
・スクリプト、単体テストともにフォーマットをかけました。
・summary を変更しました。
・異常系テストケースを改修しました。
・エラー時のログ出力を統一しました（ピリオドの追加等）。
=> t8883: Google ドライブ: フォルダ検索　Summary の変更／単体テストの改良

google-sheets-row-append.xml
レビューをお願いします。以下を変更しました。
・summary
・異常系のテストの形式
=> t8873: Google Sheets: Append New Row -change summary and error cases

google-calendar-event-insert.xml
レビューをお願いします。
summary を変更しました。
単体テストの異常系テストケースの改修をしました。
ログ出力を統一しました。（ピリオドの追加）
スクリプト、単体テストコードともにフォーマットをかけました。
=> t8882 Google カレンダー: 予定追加　Summary の変更／単体テストの改良

google-sheets-row-append.xml
レビューをお願いします。
すみません。日本語のsummaryを元に戻した時に「この工程は、」をつけ忘れてしまいました。
=> t8873: Google Sheets: Append New Row - Change summary

excel-row-insert.xml
レビューをお願いします。
Summaryの変更、単体テスト改良の他に、スクリプト部分とテストコード部分にフォーマットをかけました。
=> t8870: Microsoft 365 Excel: 行挿入 Summaryの変更／単体テスト改良

google-sheets-row-append-by-table.xml
レビューをお願いします。以下を変更しました。
・summary
・異常系のテストの形式
=> t8872: Google Sheets: Append New Rows (Table type data) - Change summary and error cases

google-sheets-sheet-delete.xml
レビューをお願いします。
・summary の変更をしました
・単体テストの異常系テストケースの改修をしました
・スクリプト部分、テストコード部分にフォーマットをかけました
=> t8874: Google スプレッドシート: シート削除　Summary の変更／単体テストの改良

google-sheets-choice-batchget.xml
レビューをお願いします。
・summary を変更しました。
=> t8879: Google Sheets: Download Choice Data - Change summary

google-sheets-row-get.xml
レビューをお願いします。
以下を変更しました。
・summary
・異常系のテストの形式
=> t8878: Google Sheets: Get Row - Change summary & error cases

google-sheets-sheet-add.xml
レビューをお願いします。
エラーログにステータスコードを含めました。
summary を変更しました。
異常系のテストの形式を変更しました。
スクリプト、テストコードともにフォーマットをかけました。
=> Google スプレッドシート: シート追加　Summary の変更／単体テストの改良

google-sheets-file-create.xml
レビューをお願いします。
以下の対応をしました。
・9036: 9024 の影響を受ける、標準アイテムの対応　の対応
・summary の変更
・単体テストの異常系テストケースの改修
・スクリプト部分、テストコード部分にフォーマット
=> t8877: Googleスプレッドシート: ファイル作成 Summary の変更／単体テストの改良

excel-row-insert.xml, google-calendar-event-insert.xml, google-calendar-event-move.xml, google-sheets-row-append-by-table.xml, google-sheets-row-append.xml, google-sheets-row-update.xml, google-sheets-sheet-add.xml, google-sheets-sheet-copy.xml, google-sheets-sheet-delete.xml, onedrive-file-copy.xml
レビューをお願いします。
以下 10 アイテムについて、単体テストの　application/json; charset=UTF-8 　でチェックしているところを、application/json に変更しました。
google-calendar-event-insert.xml
google-calendar-event-move.xml
google-sheets-sheet-add.xml
google-sheets-sheet-copy.xml
google-sheets-sheet-delete.xml
google-sheets-row-append.xml
google-sheets-row-append-by-table.xml
google-sheets-row-update.xml
onedrive-file-copy.xml
excel-row-insert.xml
=> t9036: 9024 の影響を受ける、標準アイテムの対応

onedrive-file-copy.xml
=> T9053: Microsoft 365 OneDrive for Business: ファイル / フォルダコピー　コピー完了を待てるように

google-sheets-choice-batchget.xml
=> T9026: Google スプレッドシート: 選択肢データの一括取得　日付データは日付として取得されるように

excel-row-insert.xml
ワークシートの ID を取得し、シート名でなく ID を使って更新するように。
=> T8631-2: Microsoft 365 Excel: 行挿入　シートのタイトルに半角カッコが含まれているとスクリプトエラー

generator-textfile.xml
レビューをお願いします。
ソースコード、テストコードを修正しました。
=> t9021:テキストファイル生成　保存する際の文字コードを指定できるように

kintone-record-add.xml
レビューをお願いします。
スクリプトコード、テストコードともにフォーマットもかけました。
=> t9189 kintone: レコード追加　auth-type で認証設定のタイプを限定する

kintone-record-delete.xml
レビューをお願いします。
スクリプトコード、テストコードともにフォーマットもかけました。
=> t9190 kintone: レコード削除　auth-type で認証設定のタイプを限定する

converter-textfile-to-string.xml
レビューをお願いします。以下を変更しました。
・ファイル型データ項目を読み込む際の文字コードを追加
・上記に伴う本体コードとテストコードを修正
=> t9022: Converter (Text File to String type data) - add character encoding

kintone-record-update.xml
レビューをお願いします。
スクリプトコード、テストコードともにフォーマットもかけました。
=> 9193: kintone: レコード更新　auth-type で認証設定のタイプを限定する

sendgrid-contact-upsert-custom-fields.xml
=> T9237: Twilio SendGrid: 宛先追加/更新（カスタムフィールド）　の作成

sendgrid-email-send-bulk.xml
=> T9245: Twilio Sendgrid: メール一斉送信　いくつかの設定項目の form-type 変更

sendgrid-contact-upsert.xml
=> T6960: Twilio SendGrid: 宛先追加/更新　の作成

trello-card-create.xml
=> T9212: Trello: カード作成　の作成

kintone-record-get.xml
レビューをお願いします。
スクリプトコード、テストコードともにフォーマットもかけました。
=> t9191: kintone: レコード取得　auth-type で認証設定のタイプを限定する

box-sign-request-monitor.xml
=> T9254: Box Sign: 署名リクエスト作成　署名完了を待てるように

adobe-html-to-pdf.xml
=> T9247: Adobe: PDF 生成（HTML to PDF）　の作成

chatgpt-chat-completion.xml
=> C3 となるべき config が C2 になっていた。

chatgpt-chat-completion.xml
=> help-page-url を修正など

sendgrid-email-send.xml
=> T9331: Twilio SendGrid: メール送信　の作成

box-sign-request-cancel.xml
=> t9348 Box Sign: 署名リクエストキャンセル　の作成

trello-listid-get.xml
=> t9362: Trello: リスト ID 取得　の作成

box-file-delete.xml
以下を変更しました。レビューをお願いします。
・engine-type を 3 に変更
・認証設定の変更
=> t9397: Box: Delete File - Change engine-type and auth-type setting

trello-labelid-get.xml
=> t9363 Trello: ラベル ID 取得　の作成

trello-memberid-get.xml
=> t9364 Trello: メンバ ID 取得　の作成

trello-card-create.xml
=> T9346: Trello: カード作成　標準アイテムに追加　9212

onedrive-file-link-create.xml, onedrive-file-link-delete.xml
「Microsoft 365 OneDrive for Business: 共有リンク削除」の修正と改良も含む。
=> T9458: Microsoft 365 OneDrive for Business: 共有リンク削除　の作成

start_event/onedrive-file-uploaded.xml
=> T9457: 開始: Microsoft 365 OneDrive for Business: ファイルアップロード時　の作成

aws-bedrock-stable-diffusion-image-generate.xml
=> T9577: Amazon Bedrock: Stable Diffusion: 画像生成　の作成

openai-dalle-image-generate.xml
config のラベルを修正しました。
`last-modified` が同じだとややこしいかと思い、翌日の日付にしてあります。
=> T9541: OpenAI DALL-E: 画像生成　の作成

onedrive-folder-create.xml
<addon-version>2</addon-version>　を設定しました。
ご確認をお願いします。
=> t9447: Microsoft 365 :フォルダ作成　engine-typeの変更、auth-typeの設定、addon-versionの変更

onedrive-file-delete.xml
<addon-version>2</addon-version>の設定をしました。
レビューをお願いします。
=> t9445: Microsoft 365 :ファイル/フォルダ削除　engine-typeの変更、auth-typeの設定、addon-versionの変更

onedrive-file-upload.xml
<addon-version>2</addon-version>を追加しました。
レビューをお願いします。
=> t9446: Microsoft 365 :ファイルアップロード　engine-typeの変更、auth-typeの設定、addon-versionの変更

excel-row-insert.xml
401 を 400 に変更し、ビルドが通りました。ありがとうございました。
レビューをお願いします。
=> t9443 Microsoft 365 Excel for Business: 行挿入　auth-type の設定、アイテム名の変更

box-folder-delete.xml
以下を修正しました。レビューをお願いします。
・engine-type の変更
・auth-type の設定
=> t9407: Box: Delete Folder - change engine-type, set auth-type

box-folder-create.xml
以下を修正しました。レビューをお願いします。
・engine-type の変更
・auth-type の設定
=> t9406: Box: Create Folder - change engine-type, set auth-type

box-folder-create.xml
addon-version2 を追加しました。
レビューをお願いします。
=> t9406: Box: Create Folder - add addon-version2

box-folder-delete.xml
addon-version2 を追加しました。
レビューをお願いします。
=> t9407: Box: Delete Folder - add addon-version2

box-collaboration-delete.xml
=> t9395 Box: コラボレーション削除　engine-type の変更、auth-type の設定

box-collaboration-add.xml
=> t9394 Box: コラボレーション追加　engine-type の変更、auth-type の設定

wordpress-post-create.xml
=> T9561: WordPress.com: 下書き記事作成　の作成

wordpress-category-get.xml
=> T9646: WordPress.com: カテゴリ取得　の作成

wordpress-tag-get.xml
WordPress.com: カテゴリ取得　を参考にして作成しました。
ご確認をお願いいたします。
=> t9647 WordPress.com: タグ取得　の作成

box-folder-search.xml
=> t9410 Box: フォルダ検索　engine-type の変更、auth-type の設定

box-sign-request-monitor.xml
=> t9412 Box Sign: 署名リクエストの進捗確認　AuthSettingWrapper を使用するように

google-sheets-cell-updateandget.xml
セル更新時のパラメータ `valueInputOption` について迷っています。
詳細はチケットに記載します。
=> T7860: Google スプレッドシート: セル更新＆取得　の作成

google-sheets-file-create.xml
=> t9684 Google スプレッドシート: ファイル作成　engine-type の変更

box-folder-watermark-apply.xml
=> t9411 Box: フォルダに電子すかし適用　engine-type の変更、auth-type の設定

google-sheets-sheet-add.xml
レビューをお願いします。
異常系のテストコードの処理を以下に修正しました。
```
/**
* 異常系のテスト
* @param func
* @param errorMsg
*/
const assertError = (func, errorMsg) => {
let failed = false;
try {
main();
} catch (e) {
failed=true;
}
if (!failed) {
fail();
}
};
```
=> t9689 Google スプレッドシート: シート追加　engine-type の変更、auth-type の設定

google-sheets-sheet-copy.xml
レビューをお願いします。
異常系のテストコードの処理を以下に修正しました。
```
/**
* 異常系のテスト
* @param func
* @param errorMsg
*/
const assertError = (func, errorMsg) => {
let failed = false;
try {
main();
} catch (e) {
failed=true;
}
if (!failed) {
fail();
}
};
```
=> t9690 Google スプレッドシート: シートコピー　engine-type の変更、auth-type の設定

google-drive-folder-create.xml
=> t9680 Google ドライブ: フォルダ作成　engine-type の変更

google-drive-file-delete.xml
=> t9679 Google ドライブ: ファイル / フォルダ削除　engine-type の変更

google-drive-permission-delete.xml
=> t9683 Google ドライブ: 共有リンク削除　engine-type の変更

google-drive-permission-create.xml
=> t9682 Google ドライブ: 共有リンク作成　engine-type の変更

google-calendar-event-insert.xml
=> t9677 Google カレンダー: 予定追加　engine-type の変更

google-calendar-event-delete.xml
=> t9676 Google カレンダー: 予定削除 engine-type の変更

google-calendar-event-move.xml
=> t9678 Google カレンダー: 予定のカレンダー移動　engine-type の変更

any-website-file-download.xml
レビューをお願いします
engine-type を 3 に変更しました
addon-version を 2 に設定しました
廃止予定の authSetting(String) の使用をやめる対応をしました
=> t9895 (任意Webサイト): ファイル ダウンロード　engine-type の変更／廃止予定の authSetting(String) の使用をやめる

box-folder-search.xml
=> t9888 Box: フォルダ検索　廃止予定の authSetting(String) の使用をやめる

excel-row-insert.xml
=> t9889 Microsoft 365 Excel for Business: 行挿入　廃止予定の authSetting(String) の使用をやめる

trello-card-create.xml
レビューをお願いします。
廃止予定の getOAuth2Token() の使用をやめました
=> t9886 Trello: カード作成　廃止予定の getOAuth2Token(String) の使用をやめる

docraptor-pdf-generate.xml
=> t9894 DocRaptor: PDF 生成　廃止予定の authSetting(String) の使用をやめる

kintone-record-add.xml, kintone-record-delete.xml, kintone-record-get.xml, kintone-record-update.xml, start_event/kintone-record-datetime-field.xml
=> t9885 kintone アイテム　廃止予定の getOAuth2Token(String) / authSetting(String) の使用をやめる

google-sheets-row-append-by-table.xml
新しくブランチを作成し、ファイルを修正しました。
レビューをお願いします。
=> t9553 Google スプレッドシート: 行追加 (テーブル型データ)　サブデータ項目の指定を form-type="SELECT_LIST_SUB_DATA" に変更する

box-folder-move.xml
テストで指摘いただいたエラーになるケースについて、あらかじめチェックできるものについては、事前にスクリプトエラーにするようにしました。
=> T10041: Box: フォルダ移動　の作成

converter-excelcsv-to-table.xml
コンフィグラベル D の指摘、提案をいただき修正しました。
ご確認をお願いいたします。
=> t10061 コンバータ (TSV ファイル to テーブル型データ)読み込む際の文字コードを指定できるように

google-vertexai-gemini-chat.xml
モデル追加に伴い、
- 音声ファイルを添付できるように
- 添付ファイル数の上限チェックを削除
- 温度に 2 まで指定できるように
=> T10110: Google Vertex AI: Gemini: チャット　選択可能なモデルに Gemini 1.5 Pro / Gemini 1.5 Flash の追加

converter-file-copy.xml
巽さんに提案いただき、サマリー、ラベルを修正しました。
ご確認をお願いします。
=> t7099 コンバータ (ファイルコピー)の作成

google-drive-file-export.xml
~~チケットに詳細を記載しますが、アイテム名を変えたほうが良いかもしれません。~~
アイテム名を変更しました。
=> T9931: Google ドライブ: ファイルを PDF でダウンロード

converter-excelcsv-to-table.xml
エラーメッセージを修正しました。
ご確認をお願いいたします。
=> t10164 コンバータ (TSV ファイル to テーブル型データ)　列数が合わない場合のエラーメッセージを修正

trello-card-archive.xml
=> t9358 Trello: カードをアーカイブ　の作成

trello-card-archive.xml
@tatsumiQ さん
エラーメッセージにカード ID を出力するように修正しました。
ご確認をお願いします。
=> t9358 Trello: カードをアーカイブ の作成 -エラーメッセージにカード ID を出力

trello-card-move.xml
=> t9359: Trello: カード移動　の作成

github-repository-collaborater-add.xml
@tatsumiQ さん
招待取者を得しきれない場合の処理とそのテストケースを追加しました。
ご確認をお願いします。
=> t10183 GitHub: リポジトリコラボレーター追加   招待者を取得しきれない場合の処理を追加

github-repository-collaborater-remove.xml
@tatsumiQ さん
定義ファイルを作成しました。
ご確認をお願いします。
=> t10184 GitHub: リポジトリコラボレーター削除　の作成

generator-textfile.xml
=> t10200 テキストファイル生成　保存する際のファイルタイプに Markdown を追加する

chatgpt-chat-completion.xml
=> t10249&t10250 OpenAI ChatGPT: チャット　o1-preview / o1-mini モデル追加  回答保存データ項目に、文字型 Markdown 追加

google-drive-file-export.xml
=> t10326 Google ドライブ系アイテム　アイコンの変更

aws-bedrock-anthropic-claude-chat.xml
@tatsumiQ さん
定義ファイルを修正しました。ご確認をお願いします。
=> t10328&10304 Amazon Bedrock: Anthropic Claude: チャット モデルの追加、削除  文字型 Markdown の追加

aws-bedrock-anthropic-claude-chat.xml
@tatsumiQ さん
クロスリージョン推論への対応をしました。ご確認をお願いします。
=> t10394 Amazon Bedrock: Anthropic Claude: チャット　クロスリージョン推論への対応

google-drive-folder-search.xml
=> t10117 Google ドライブ: フォルダ検索　廃止予定の「C1-deprecated: OAuth2設定」の削除

aws-bedrock-stability-ai-image-generate.xml
@tatsumiQ さん
レビューをお願いします。
テストコードのリージョンは、現在可能な　us-west-2　のみにしています。
=> t10387 Amazon Bedrock: Stability AI: 画像生成　の作成

chatgpt-chat-completion.xml
モデルに o1 / o3-mini を追加しました。ご確認をお願いします。
=> t10497 OpenAI ChatGPT: チャット　モデルに o1 / o3-mini を追加する

github-file-get.xml
@tatsumiQ  さん
定義ファイルを作成しました。ご確認をお願いします。
チケットにも記載しましたが、テストコードの保存されたファイルのテスト（最後のテストケース 2 つ）で失敗します。
ファイル型データ項目に保存されたファイル数を確認するテスト
expect(files.size()).toEqual(1);
で、以下のエラーが出ます。
javax.script.ScriptException: TypeError: invokeMember (size) on com.questetra.bpms.core.event.scripttask.NewQfile
テストコードで、ファイルの保存自体ができていないということでしょうか？
=> t10533 GitHub: ファイル取得　の作成

aws-bedrock-anthropic-claude-chat.xml
=> T10544: Amazon Bedrock: Anthropic Claude: チャット　モデルの選択肢に Claude 3.7 Sonnet を追加し、拡張思考モードに対応する

github-file-delete.xml
@tatsumiQ  さん
現在、スクリプトを作成中で、テストコードは作成していない状態です。
QBPMS でテストした結果について、分からないことがあるので教えてください。
147 行目くらいのところで、
```
const response = httpClient.begin()
.header(API_VERSION_HEADER, API_VERSION)
.header("accept", "application/vnd.github+json")
.authSetting(auth)
.body(JSON.stringify(jsonReq), "application/json; charset=UTF-8")
.delete(url);
```
「スクリプトエラーが発生しました。  at line number 104」とエラーになります。
ステータスコードが返ってきません。
throw new Error(`Failed to delete a file. status: ${status}`);
ステータスコードを返す処理にまでにエラーが起こっているのかと思います。
ヘッダの設定の仕方等に問題があるときに起こるエラーなのでしょうか？
=> t10333 GitHub: ファイル削除　の作成

github-file-commit.xml
@tatsumiQ さん
スクリプト、テストコードを作成しました。
レビューをお願いします。
=> t10332 GitHub: ファイルアップロード／更新　の作成

aws-bedrock-stability-ai-image-generate.xml
レビューをお願いします。
tability 3 Large　の削除が漏れていたので、このモデルも削除しました。
Stable Image Ultra 1.1　ですが、廃止予定の記載を見つけられなかったので、残しています。
=> t10630 Amazon Bedrock: Stability AI: 画像生成 廃止予定のモデルを削除

chatgpt-chat-completion.xml
@tatsumiQ さん
モデルを入れ替えました。レビューをお願いします。
コラボチャットにも記載していますが、o1-pro、　o3-pro は、エンドポイントが　v1/chat/completions　に対応していないので追加しておりません。
=> t10689 OpenAI ChatGPT: チャット　モデルを入れ替える

aws-bedrock-anthropic-claude-chat.xml
@tatsumiQ さん
定義ファイルを修正しました。
ご確認をお願いします。
=> t10827 Amazon Bedrock: Anthropic Claude: チャット　モデルを入れ替える

openai-dalle-image-generate.xml
@tatsumiQ さん
サマリーを修正しました。
ご確認をお願いします。
=> t10690 OpenAI DALL-E: 画像生成　サマリーを修正

openai-dalle-image-generate.xml
@tatsumiQ さん
何度もすみません。
JPEG の拡張子を修正しました。ご確認をお願いします。
=> t10690 OpenAI DALL-E: 画像生成　JPEG の拡張子を修正
