Questetra/Addon-XML

LINENotify.xml
#8 
OAuthの設定が出来ていれば投稿できるはずです。
>Client ID / Secret は、オープン（誰にでも見える）にして良いものではない
LINE Notifyの仕様的に、Client ID / Secret はHelpあたりに書かざるを得ないわけですが、それは大丈夫なのでしょうか(サービスごとにClient ID / Secretが存在する仕様です。本来はアプリ内で(ユーザーに見えない形で)token取得を行うことが想定されているようなので)。
=> Add LINENotify.xml

google-calendar-insert-event.xml
#62 
License表記を変更
Google Calendar → Google カレンダー に
=> Google Calendarアドオンの修正2つ

GoogleSheets-appendCells.xml, google-sheets-choice-batchget.xml
Google Sheets 選択肢データの一括取得
再テスト後、C1のラベルを修正したところまで。
Google Sheets 行追加
途中です。
C4以降が空だった時の挙動をとりあえず「空文字を送る」に戻してあります。
=> Google Sheets 関連アドオン

google-drive-folder-search.xml
>エラーをするとき、"Such folder" ではなく、"Folder ○○" と ○○にフォルダ名を入れるようにしてください。
に対応。同時にトークン周りを変更。
=> Google drive

box-folder-create.xml
・重複していないとき、作成される
・フォルダと重複しているとき、元あったフォルダのIDが返される
・ファイルと重複しているとき、スクリプトエラーになる
・重複以外のエラーが出たとき、スクリプトエラーになる
以上テスト済み。
=> フォルダ名重複時エラーにならないように

google-sheets-row-append-by-table.xml
数値型で空白だとエラーが出るのを修正
空白の場合は設定に関係なく文字型の空文字を追加するように(nullを入れない場合は)した。
テスト : https://docs.google.com/spreadsheets/d/122G8ylw8ql-Io9B3_ZEjalReAddPHNScm6CVaNXMmiE/edit#gid=0
=> Google スプレッドシート: 行追加 (テーブル型データ項目) 

onedrive-file-copy.xml
フォルダコピーへの対応のため、設定項目のラベルやアドオン名を変更しました。
分かりやすさのため、併せてconfig名、変数・関数名、コメント等も修正しています。
ご確認いただき、問題なければ merge をお願いします。
=> Microsoft 365 OneDrive for Business: ファイルコピー　フォルダコピー対応

onedrive-file-copy.xml
ヘルプページ更新作業中に、英語版の summary の更新が抜けていたことに気づきました。
　更新前）Creates a copy of a file into the specified folder on OneDrive.
　更新後）Creates a copy of a file/folder into the specified folder on OneDrive.
お手数ですが、再度マージ頂けますと幸いです。
=> Microsoft 365 OneDrive for Business: ファイルコピー　フォルダコピー対応　summaryとコメントを修正

kintone-choice-download.xml
指摘箇所の修正の際、再帰呼び出しの引数の修正が抜けていました。
このままだと500件以上のデータが取得できないため、修正のプルリクエストをさせていただきます。
=> T7428: kintone: 選択肢データの一括取得　再帰呼び出し部分の修正

converter-dateToJpEra.xml
=> T7407：コンバータ（Date to 和暦テキスト）　エンジンを GraalJS に変更する

google-drive-folder-search.xml
以下の点を修正しました。
- GraasJSに対応
- TypeErrorを解消
httpClient の queryParam の数字で型変換エラーが発生。明示的に String にキャストすることで解消。既知のバグ。
103行目
```
.queryParam("pageSize", 1000)
```
↓
```
.queryParam("pageSize", String(1000))
```
=> t7394:Google ドライブ: フォルダ検索　エンジンを Nashorn から GraalJS に変更する

gmail-message-get.xml
以下の点を修正しました。
* 未設定の保存先データ項目があっても動作するように
* To/Cc/Bcc のメールアドレス、表示名一覧が To → Cc → Bcc の順になるように
未対応事項
* アイコンの設定（IconMaker への登録待ち）
=> T7516：Gmail: メール取得　未設定の保存先データ項目があっても動作するように

start_event/box-file-uploaded.xml
フォルダ内のアイテム数が 1000 を超える場合、動作しない。
=> アイテムの取得を１度に抑えるように変更。

google-calendar-event-insert.xml
以下の変更を行いました。
- 文字型データ項目(`eventDescription`, `eventLocation`)のどちらかが空でない場合、Meet URL を作成。
- 説明情報を`TEXTFIELD`から`TEXTAREA`に変更。
=> T7395:文字型データ項目に保存する場合のみ、Meet URL を作成

start_event/kintone-record-datetime-field.xml
アイテムの設定によっては、order by と limit が入らない状態になっていた。
=> 検索クエリを構成するロジックの修正

box-file-copy.xml
変更点
- 設定名の変更(C1,C5,C6)
- bearer() の使用を authSetting() に変更
- last-modified の更新
- インデントの修正
- 194～201行、処理を修正
- エラーメッセージの変更(statusを省く)
=> OAuth2 認証まわりのコード変更

box-folder-link-create.xml
改修点
- 設定名の変更。OAuth2 設定名 -> OAuth2 設定
- bearer() の使用を authSetting() に変更
- last-modified の更新
- config のlabel を修正
- ステータスコードを常に出力するように
- エラーメッセージを一部変更
=> Box: フォルダ共有リンク作成 OAuth2 認証まわりのコード変更

google-calendar-event-insert.xml
=> Google カレンダー: 予定追加　ヘルプページ URL の修正

onedrive-file-upload.xml
t7470: Microsoft 365 OneDrive for Business: ファイルアップロード　ファイル型データ項目に、同じ名前のファイルが複数添付されている場合、必ずファイルアップロードに失敗するように
t7482: Microsoft 365 OneDrive for Business: ファイルアップロード　アップロードするファイルと同じ名前のファイルが、 OneDrive に既に存在する場合、上書きせずエラーとなるように
t7796: Microsoft 365 OneDrive for Business: ファイルアップロード　OAuth2 認証まわりのコード変更
以上のチケットに関する変更。
=> Microsoft 365 OneDrive for Business: ファイルアップロード

google-calendar-event-move.xml
予定をカレンダー移動すると、予定 URL が変わる。（もしかしたら、変わらない場合もあるかもしれない)
予定 URL を再取得して、保存する機能を追加。
- last-modified の変更
- config C5 を追加
- script の変更
以外は、インデントを整えただけです。
=> T7737 予定 URL を保存できるように

converter-excelcsv-to-table.xml
単体テストのテーブル型データ項目よりも多い列数(over-columns)にて`Incorrect number of rows at line 2`となるようにしました。
=> T7985:カラム数が違う時に行数が正しく表示されるように修正

box-file-download.xml
以下の項目をテストする。
- ファイルIDが空の場合
- 404エラーが返ってくる場合
- 403エラーが返ってくる場合
- ファイル型データ項目に他のファイルが入っていない状態でダウンロードに成功した場合
- ファイル型データ項目に他のファイルが入っている状態でダウンロードに成功した場合
- ファイル名の指定をせずにダウンロードに成功した場合(ファイル型データ項目に他のファイルは入っていない)
=> t8086:Box: ファイルダウンロード　単体テストの追加

google-drive-permission-create.xml
畠中さん
レビューをお願いします。
* URLの取得の処理の際に{{{queryParam("supportsAllDrives", "true")}}}を追加し、エラーの場合throwする処理を追加
* 単体テストコードに「GET API リクエストでエラー」のケースを追加
=> fix URL acquisition process, add test case of GET API error

google-calendar-event-insert.xml
375行目の、「カレンダーIDにサポート外の文字が含まれていてエラーになる場合」のテストが通りません。
エラーメッセージが、以下になるのですが、これはどういう意味でしょうか
Expected: a string ending with "Invalid Calendar ID"
but: was "
Unexpected method call QbpmConfiguration.getLocale():"
=> ハイフンを含むカレンダーIDに対応

google-sheets-row-get.xml
以下の事柄についての単体テストを追加
・行指定が不適切
・行番号が空
・列指定が不適切
・同じデータ項目を異なる列の出力に指定
・正常に取得できる
・404エラー
・取得した部分のセルがすべて空
=> Google スプレッドシート: 行取得　単体テストの追加

slack-chat-post-bots.xml
``@hatanaka-akihiro  さん
テストコード　337 行目以降
チャット投稿失敗の場合（存在しないチャンネル）について質問です。
このテストは、エラーですが、ステータスコード200で、レスポンスオブジェクトも返します。
ビルドすると、下記エラーになります。
```
org.graalvm.polyglot.PolyglotException: 
Expected: a string containing "Failed to send"
but: was "function is expected to be throw error"
```
`expect(execute).toThrow(`Failed to send`);`
と書いてはいけないのでしょうか？
=> t8322 単体テストコードを追加

kintone-record-add.xml
教えてください。
リクエストのテストを検証するコードで、398 行目
`expect(bodyObj.record).toEqual(recordObj);`
でビルドが失敗します。オブジェクトの検証が間違っているのでしょうか
（テストコードは、この処理をコメントアウトして、ビルドを通して作成しています。）
=> t8319: kintone: レコード追加　単体テストの追加／summary の変更

stripe-invoice-create.xml
=> T8601: Stripe: 請求書ドラフト作成　通貨を指定できるように

slack-chat-post-webhook.xml
単体テストコードを追加しました。
summary の変更をしました。
ご確認をお願いいたします。
変更元のコードは、以下のものを流用しました。
https://raw.githubusercontent.com/Questetra/Addon-XML/release-2021-08-26/slack-chat-post-webhook.xml
アイコンの色がグリーンで、標準アイテムの紫と異なります。
こちらのファイルで、どこか設定する箇所があれば教えてください。
=> Slack: チャット投稿 (Incoming Webhook)単体テスト追加／summaryの変更

stripe-product-create.xml
商品説明が空の場合、パラメータにセットしないように変更しました。
（パラメータにセットしてしまうと、API リクエストでエラーになるため）
=> T8625: Stripe: 商品を作成

box-folder-delete.xml
スクリプト部分、テストコード部分にフォーマットをかけました。
8752 Box: ファイル削除　Summary の変更／Nashorn Compatible モード取りやめを見越した単体テストの改良
を参考にして、Summary の変更、単体テストの改良のほか、ログ出力を整形してステータスコードをエラーメッセージに含めるようにしました。
ご確認をお願いします。
=> 8854: Box: フォルダ削除　Summary の変更／単体テストの改良

google-calendar-event-delete.xml
レビューをお願いします。
スクリプト：
ログ出力を統一しました。（ピリオドの追加）
エラーメッセージにステータスコードを含むようにしました。（処理成功の場合は、ステータスコードを出力しないようにしました）
フォーマットをかけました。
テストコード：
異常系テストケースを改修しました。
フォーマットをかけました。
=> t8880: Google カレンダー: 予定削除　Summary の変更／単体テストの改良

box-file-representation-download.xml
- 代わりに `engine.saveTemporaryData()` `engine.restoreTemporaryData()` を使用するように改良。
- 単体テストの変更。
=> conf_urlTemplate を削除

onedrive-file-upload.xml
ファイルサイズによらずセッションアップロードに一本化。
副作用として、
- 一度にアップロードできるファイル数上限が減った
- サイズ 0 のファイルをアップロードできなくなった
=> T9009: Microsoft 365 OneDrive for Business: ファイルアップロード　PUT リクエスト時の Content-Type を application/octet-stream 固定にするか、ファイルサイズによらずセッションアップロードに一本化する

sendgrid-email-send-bulk.xml
「値を１つ設定する」設定項目は、
```
form-type="SELECT" select-data-type="STRING_TEXTFIELD|SELECT_SINGLE" editable="true"
```
に。
「値を複数設定できる」設定項目は、
```
form-type="SELECT" select-data-type="STRING|SELECT"
```
に。
後者にも `editable="true"` をつけて固定値を指定できるようにしたいが、1 つしか指定できなくなる。
それでもいいという考えもあるが、いったん「Twilio SendGrid: 宛先追加/更新」と合わせて、`editable="true"` はなしにした。
=> T9245: Twilio Sendgrid: メール一斉送信　いくつかの設定項目の form-type 変更

slack-userid-get.xml
@yehara さん
レビューをお願いします。
ファイル名は、slack-userid-get　としました。
コンフィグは、以下にしました。
C1: 認証設定（必須）
C2: ユーザもしくはメールアドレス（必須）
C3: ユーザ ID を保存する文字型データ項目
=> t9341 Slack: ユーザ ID 取得　の作成

box-sign-request-cancel.xml
英文の指摘を修正しました。ご確認をお願いします。
summary について 
This item cancels a specified sign request on Box.
を以下に修正しました。
This item cancels the specified sign request on Box.
400　エラー時のログ出力について
The status can be "Signed", "Canceled","Declined", or "Converting".
を以下に修正しました。"Canceled"と"Declined"の間にスペースを加えました。
The status can be "Signed", "Canceled", "Declined", or "Converting".
=> t9348 Box Sign: 署名リクエストキャンセル　の作成

trello-listid-get.xml
英語の表記を修正しました。ご確認をお願いします。
C5 
Data item to save ID of the list
を
Data item to save List ID
に修正しました。
list を List にしましたが、他のアイテムに習い、summary の list は小文字のままにしています。
=> t9362 Trello: リスト ID 取得　の作成

slack-message-post.xml, slack-userid-get.xml
Questetra が登録済みの Bot でも使用できるよう対応しました。
QBPMS 上では動作確認できたのですが、テストコードで失敗します。
https://sanjo.questetra.net/jenkins/job/userweb_test_addon/3580/com.questetra$bpms/console
このエラーはどういう意味か教えてください。
設定の準備で、認証設定の以下の箇所が間違えているのでしょうか？
```
const auth_OAuth2_V2 = httpClient.createAuthSettingOAuth2(
'Slack',
'https://slack.com/oauth/v2/authorize',
'https://slack.com/api/oauth.v2.access',
'chat:write,users:read,users:read.email',
'consumer_key',
'consumer_secret',
'access_token'
);
configs.putObject('conf_OAuth2_V2', auth_OAuth2_V2);
```
=> t9418 Slack: ユーザ ID 取得　Questetra が登録済みの Bot でも使用できるように

slack-message-post.xml
=> t9418 Slack: メッセージ送信 (Block Kit 対応) Questetra が登録済みの Bot でも使用できるように

trello-listid-get.xml
レビューをお願いします。
英語のラベルを　Trello: Get List ID　に修正しました。
他、別のアイテムで指摘があったので、こちらのアイテムでも修正しました。
・ボード ID をパスパラメータに含める部分で encodeURIComponent()　を使用しました。
・クエリパラメータの key と token について、queryParam() を使用しました。
=> t9419 Trello: リスト ID 取得 　ラベルの修正等

trello-labelid-get.xml
レビューをお願いします。
・英語のラベルを　Trello: Get Label ID　に修正しました。
・ボード ID をパスパラメータに含める部分で encodeURIComponent()　を使用しました。
・クエリパラメータの key と token について、queryParam() を使用しました。
=> t9363 Trello: ラベル ID 取得　英語のラベルを修正

trello-memberid-get.xml
レビューをお願いします。
・英語のラベルを　Trello: Trello: Get Member ID　に修正しました。
・英語のラベル（C4）を　( の前に半角スペースを追加し、Full Name or User Name; write one per line とし、区切り文字をセミコロンにして、write の語頭を小文字にしました。
・ボード ID をパスパラメータに含める部分で encodeURIComponent()　を使用しました。
・クエリパラメータの key と token について、queryParam() を使用しました。
=> t9364 Trello: メンバ ID 取得  英語のラベルを修正

onedrive-file-copy.xml
=> t9444 Microsoft 365 OneDrive for Business: ファイル / フォルダコピー　auth-type の設定

sendgrid-email-send-bulk.xml
* カテゴリを C6-B の設定と同一タブの末尾に移動させ、連番を C7 から C6-B4 に変更しました
* タブ名「メール本文」を変更するか迷いましたが、そのままにしました
=> T9611: Twilio SendGrid: メール一斉送信　C7 の設定を C6-B の設定と同一タブにする

onedrive-file-delete.xml
=> t9445 Microsoft 365 OneDrive for Business: ファイル / フォルダ削除　engine-typeの変更、auth-type の設定

onedrive-folder-create.xml
=> t9447: Microsoft 365 OneDrive for Business: フォルダ作成　engine-type の変更、auth-type の設定

onedrive-file-upload.xml
=> t9446: Microsoft 365 OneDrive for Business: ファイルアップロード　engine-type の変更、auth-type の設定

box-file-link-create.xml
=> t9399 Box: ファイル共有リンク作成　engine-type の変更、auth-type の設定

box-file-link-delete.xml
=> t9400 Box: ファイル共有リンク削除　engine-type の変更、auth-type の設定

box-file-copy.xml
レビューをお願いします。
auth-type を指定し、認証設定で AuthSettingWrapper? を利用するように修正しました。
=> t9396 Box: ファイルコピー　engine-type の変更、auth-type の設定

box-file-download.xml
レビューをお願いします。
auth-type を指定し、認証設定で AuthSettingWrapper? を利用するように修正しました。
=> t9398 Box: ファイルダウンロード　engine-type の変更、auth-type の設定

box-file-metadata-add.xml
=> t9401 Box: ファイルにメタデータ追加　engine-type の変更、auth-type の設定

box-folder-link-create.xml
=> t9408 Box: フォルダ共有リンク作成　engine-type の変更、auth-type の設定

box-folder-link-delete.xml
=> t9409 Box: フォルダ共有リンク削除　engine-type の変更、auth-type の設定

box-file-move.xml
=> t9402 Box: ファイル移動　engine-type の変更、auth-type の設定

box-file-representation-download.xml
レビューをお願いします。
auth-type を指定し、認証設定で AuthSettingWrapper? を利用するように修正しました。
=> t9403 Box: ファイルを PDF/テキスト/画像でダウンロード　engine-type の変更、auth-type の設定

box-file-upload.xml
=> t9404 Box: ファイルアップロード　engine-type の変更、auth-type の設定

google-vertexai-gemini-chat.xml
また単体テストのテストケースに、response が複数のパートに分かれているケースを追加。
=> response が複数のパートに分かれている場合の、結合方法を変更。

box-file-watermark-apply.xml
=> t9405 Box: ファイルに電子すかし適用　engine-type の変更、auth-type の設定

box-folder-watermark-apply.xml
=> t9411 Box: フォルダに電子すかし適用　engine-type の変更、auth-type の設定

google-sheets-sheet-add.xml
=> t9689 Google スプレッドシート: シート追加　engine-type の変更、auth-type の設定

google-sheets-sheet-copy.xml
=> 9690 Google スプレッドシート: シートコピー　engine-type の変更、auth-type の設定

google-sheets-sheet-delete.xml
=> t9691 Google スプレッドシート: シート削除　engine-type の変更、auth-type の設定

google-sheets-row-get.xml
レビューをお願いします。
テストコードの異常系の処理を以下にしました。
```
/**
* 異常系のテスト
* @param func
* @param errorMsg
*/
const assertError = (func, errorMsg) => {
let failed = false;
try {
main();
} catch (e) {
failed=true;
}
if (!failed) {
fail();
}
};
```
=> t9687 Google スプレッドシート: 行取得　engine-type の変更、auth-type の設定

google-sheets-row-update.xml
レビューをお願いします。
変更箇所を見ていただきたかったので、スペース 4 でフォーマットをかけていません。スペース 2 のままです。
コンフィグに、「C4: 行更新時の値の解釈方法」を追加し、値の解釈方法を選択できるように処理しました。
日本語のみ、「C6_1: 列範囲のうち 2 列目の更新後の値」の序数が「C6_1: 列範囲のうち 1 列目の更新後の値」と同じになっていたので修正しました。
=> t9688&9732 Google スプレッドシート: 行更新　engine-type の変更、auth-type の設定 値の解釈方法を選択できるように

google-sheets-row-append.xml
レビューをお願いします。
シート名がセル指定や名前付き範囲として誤って解釈されないように修正しました。
=> t9686&t9757 Google スプレッドシート: 行追加 engine-type の変更、auth-type の設定 シート名がセル指定や名前付き範囲として誤って解釈されないように

google-drive-folder-search.xml
=> t9681 Google ドライブ: フォルダ検索　engine-type の変更、auth-type の設定

start_event/google-calendar-event-started.xml
- engine-type を 3 に変更
- addon-version を 2 に変更
- 日時フォーマットの定義を整理し、QBPMS のタイムゾーン依存のテストが失敗しないように
=> T9692: 開始: Google カレンダー: 予定開始時　engine-type の変更

google-vertexai-gemini-chat.xml
=> T9804: Google Vertex AI Gemini: チャット　scope を HTTP 認証設定で行うように

google-sheets-row-append-by-table.xml
=> t9685 Google スプレッドシート: 行追加 (テーブル型データ)　engine-type の変更、auth-type の設定

google-bigquery-data-insert.xml
レビューをお願いします。
addon-version を 2 に設定しました。
summary を修正しました。（「この工程は、」「This item」を追加）
=> t9675 Google BigQuery: データ追加　engine-type の変更、auth-type の設定、summary の変更

google-drive-file-download.xml
C1 の日本語と英語のラベルが入れ替わっていたため、修正しました。
=> T9798: Google ドライブ: ファイルダウンロード　の作成

chatgpt-chat-completion.xml
停止シーケンスを指定しない場合、パラメータ自体をセットしないように。
モデルによっては、空の配列を指定するとエラーになる場合があるため。
=> T9810-T9812: OpenAI ChatGPT: チャット　改良

gmail-message-get.xml, gmail-message-label-remove.xml, google-sheets-choice-batchget.xml, start_event/gmail-message-received.xml
レビューをお願いします。
engine-type を 3 に変更しました。(Google スプレッドシート: 選択肢データの一括取得 以外)
開始: Gmail: メール受信時　の定義ファイルは、
開始: Microsoft 365 OneDrive for Business: ファイルアップロード時　を参考にして修正しました。
https://raw.githubusercontent.com/Questetra/Addon-XML/master/start_event/onedrive-file-uploaded.xml
=> T9887 Google アイテム　engine-type の変更／廃止予定の authSetting(String) の使用をやめる

slack-chat-post-bots.xml, slack-chat-post-webhook.xml, slack-file-upload-bots.xml
レビューをお願いします。
auth-type を指定し、認証設定で AuthSettingWrapper を利用するように修正しました。(Slack: ファイルアップロード (Bots)、Slack: チャット投稿 (Bots))
廃止予定の設定を削除しました。(Slack: チャット投稿 (Bots))
=> T9890 Slack アイテム engine-type の変更／廃止予定の authSetting(String) の使用をやめる／廃止予定の設定を削除する

google-drive-folder-search.xml
C2 の親フォルダ ID を required に変更し、エラーメッセージも併せて変更しました。
=> T9942: Google ドライブ: フォルダ検索　サービスアカウント形式を導入する／既存の OAuth2 設定は廃止予定とする

converter-excelcsv-to-table.xml, converter-table-to-excelcsv.xml, google-sheets-row-append-by-table.xml
こちらのブランチに、
converter-excelcsv-to-table.xml
converter-table-to-excelcsv.xml
の定義ファイルをそのまま引き継いで改良しました。レビューをお願いします。
google-sheets-row-append-by-table.xml
については、t9553 のブランチで対応していますので、こちらのブランチでは未対応です。
=> t9973 テーブル型データ項目の値を書き換えるビルトインアイテム　ScriptListArray のチェック強化に関して単体テストの改修

converter-file-copy.xml
テストコードについて教えてください。
最後のテストケース　success - Same File type data - deleteOtherFiles - with name　について
* コピー成功
* コピー元のファイル型データ項目とコピー先のファイル型データ項目が同一
* コピー元のファイル型データには 1 ファイル添付
* 他のファイルを削除する
* ファイル名を指定
ビルドが失敗します。ファイル名を指定していますが、ファイル名が変更されていないというエラーが出ます。
expected:<[qqq].txt> but was:<[test].txt>
もともと、test.txt　の名前のファイルを、別名 qqq.txt にするテストなのですが、上記のエラーになります。
テストの書き方、設定の準備の書き方で、よくないところがあったら教えてください。
=> t7099 コンバータ（ファイルコピー）の作成

google-vertexai-gemini-chat.xml
新しいモデルでは、レスポンスの `candidates[0].content` が `undefined` になる場合があるようです。
どんな場合にそうなるかは、よくわかっていません。
その場合にも予期せぬエラーで異常終了しないよう、スクリプトを修正しました。
エラーをスローするか迷いましたが、一部の回答が返ってきている可能性もあるため、`No content in the candidate.` のプロセスログを出力したうえで、処理継続しています。
=> T10110: Google Vertex AI: Gemini: チャット　選択可能なモデルから Gemini 1.0 Pro Vision を削除　Gemini 1.5 Pro / Gemini 1.5 Flash の追加

google-vertexai-gemini-chat.xml
@tatsumiQ さん
レビューをお願いします。
PDF かどうかを判断する処理は、application から始まる種類が多そうだったので、
!contentType.startsWith('application/pdf')　にしました。
=> t10225&10305 Google Vertex AI: Gemini: チャット PDFに対応／回答を保存するデータ項目に文字型 Markdown を追加

deepl-text-translate.xml
レビューをお願いします。
異常系のテストコードについても修正しました。
=> t10470 DeepL: テキスト翻訳　認証キーを URL クエリに含めないように

aws-bedrock-anthropic-claude-chat.xml
@tatsumiQ さん
PDF ファイルを複数添付する処理で行き詰ってしまったので教えてください
D1: ユーザメッセージに添付する PDF の設定項目を設けました
PDF ファイルは、以下のように "name" プロパティの設定が必要になります
```
{
"document": {
"format": "pdf",
"name": "string",
"source": {
"bytes": "document in bytes"
}
}
}
```
"name" プロパティは、重複するドキュメント名を設定することができません
```
const inlinePdf = {
document: {
format,
name: `PDF${index}`,
source: {
bytes: base64.encodeToString(fileRepository.readFile(pdf))
}
}
};
```
上記の処理で、
"Messages can’t contain duplicate document names. Rename the document and retry your request."
というエラーになり、名前が重複している旨のエラーになります。
どの部分の処理が問題でしょうか
=> t10226 他 Amazon Bedrock: Anthropic Claude: チャット

aws-bedrock-stability-ai-image-generate.xml
@tatsumiQ さん
アイテムにとってのデフォルト値を png としました。
未指定の場合、リクエストボディの output_format に png をセットするよう修正しました。
ご確認をお願いします。
=> t10387 Amazon Bedrock: Stability AI: 画像生成　画像形式未設定の処理を修正

chatgpt-chat-completion.xml
応答が空の場合、`No response content generated. Finish Reason: {finish_reason}` のエラーをスローするようにしました。
200 レスポンスで応答が空になるのは、`finish_reason` が　`length` の場合しか確認されていませんが、`finish_reason` によらずに応答が生成されなかった場合はエラーにするようにしました。
また、この場合もトークンの内訳を確認したいかと思ったので、正常終了の場合と同じトークンの内訳をログ出力しています。
=> T10517: OpenAI ChatGPT: チャット　finish_reason: length で応答が空の場合、異常終了となるように

aws-bedrock-anthropic-claude-chat.xml
拡張思考モードでの推論を有効にした場合の、制限事項:
- 現在、対応しているモデルは Claude 3.7 Sonnet のみ
- システムプロンプト、画像ファイルの添付も、対応しているモデルが限られます。システムプロンプト、画像ファイルの添付と同様に、スクリプトで事前にバリデーションはせず、API のバリデーションに任せています。ヘルプページで、対応しているモデルが限られる旨、追記予定です
- 推論に使用するトークン数上限（budget tokens）、指定必須
- 最低値は 1024
- 全体として消費するトークン数上限（max tokens）より小さい値を指定する必要がある
- デフォルト値を 1024 とし、上記の制限については、スクリプトで事前にバリデーションするようにしました
- 温度、変更不可（指定できる温度は 1 のみ）
- スクリプトで事前にバリデーションするようにしました   
推論でトークン切れになって回答が空になるケースは、先にタイムアウトになってしまうため実際には確認できていませんが、理論上は発生しうるので、ChatGPT のアイテムと同様の修正を加えました。
=> T10544&T10599: Amazon Bedrock: Anthropic Claude: チャット　モデルの選択肢に Claude 3.7 Sonnet を追加し、拡張思考モードに対応する & 推論でトークン切れになり、応答が空の場合、異常終了となるように
